name: Deploy Docs to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
          # Install doc dependencies directly from pyproject.toml
          pip install sphinx>=7.0.0 pydata-sphinx-theme>=0.13.3 myst-parser>=1.0.0 sphinx-copybutton>=0.5.2 sphinx-design>=0.4.1 sphinxcontrib-napoleon>=0.7
          
          # Install the package in development mode (with correct path)
          pip install -e .
          
          # Verify installation
          sphinx-build --version
          
      - name: Build documentation
        run: |
          # Build docs directly with sphinx-build
          sphinx-build -b html docs/source docs/build/html
          
          # Check if build succeeded
          ls -la docs/build/html || echo "HTML build failed"
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/build/html'
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3